spring.application.name=API Empleados

#Configuraci�n MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/empleados
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Configuraci�n de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#Para ver las SQL que se ejecutan poner las siguientes (opcional)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Tamaño máximo de fichero individual
spring.servlet.multipart.max-file-size=10MB
# Tamaño máximo de la petición completa (puede llevar varios ficheros)
spring.servlet.multipart.max-request-size=20MB
# Carpeta base donde se guardarán los ficheros subidos
app.storage.location=uploads

